// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6cW003-89ggumYyidHZw4KFad2aY7-I',
    appId: '1:709614285554:web:cf25afa3ec5e69b6a4166b',
    messagingSenderId: '709614285554',
    projectId: 'event-management-c275c',
    authDomain: 'event-management-c275c.firebaseapp.com',
    storageBucket: 'event-management-c275c.firebasestorage.app',
    measurementId: 'G-89335518K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cqojrzeLZuZxE6Nml5gVZ1UH3mNguvg',
    appId: '1:709614285554:android:f51063c24ec47e9ca4166b',
    messagingSenderId: '709614285554',
    projectId: 'event-management-c275c',
    storageBucket: 'event-management-c275c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi06M9gcUBUbH049sl0Zz3JEg810KBh7Q',
    appId: '1:709614285554:ios:6f52d08b0f6af036a4166b',
    messagingSenderId: '709614285554',
    projectId: 'event-management-c275c',
    storageBucket: 'event-management-c275c.firebasestorage.app',
    iosBundleId: 'com.example.eventmvp.eventMvp',
  );
}
